general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_title = true

[window.padding]
x = 8
y = 8

[font]
size = 14

[font.glyph_offset]
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
y = 15

# [colors.primary]
# background = "#FFFFFF"
# foreground = "#000000"
#
# [colors.cursor]
# cursor = "#000000"
# text = "#FFFFFF"
#
# [colors.selection]
# background = "#D0D0D0"
# text = "#000000"
#
# [colors.normal]
# black   = "#000000"
# red     = "#CC0000"
# green   = "#009600"
# yellow  = "#D0A000"
# blue    = "#0000CC"
# magenta = "#CC00CC"
# cyan    = "#0096CC"
# white   = "#CCCCCC"
#
# [colors.bright]
# black   = "#555555"
# red     = "#FF0000"
# green   = "#00CC00"
# yellow  = "#FFD000"
# blue    = "#0000FF"
# magenta = "#FF00FF"
# cyan    = "#00CCFF"
# white   = "#FFFFFF"

[cursor.style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
